# Generated by Django 4.0 on 2022-02-17 09:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(null=True, upload_to='static/uploads/category-images')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('service_description', models.TextField(null=True)),
                ('session_time', models.IntegerField(null=True)),
                ('image', models.FileField(null=True, upload_to='static/uploads/service-images')),
                ('session_cost', models.FloatField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.category')),
            ],
        ),
    ]
